version: '3'

services:
    postgres:
        image: postgres:14-alpine
        ports:
        - "5428:5432"
        volumes:
        - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "12345"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "postgres"
        networks:
        - minha_rede

    drive-select-back:
        build:
            context: .
            dockerfile: ./Back/Dockerfile
        container_name: drive-select-back
        ports:
            - "8080:8080"
        volumes:
            - ./:/app/Back
            - /app/Back/node_modules
        environment:
            TYPEORM_HOST: postgres
            TYPEORM_PORT: 5432
            Environment: prod
        tty: true
        depends_on:
        - postgres
        restart: always
        networks:
        - minha_rede
        env_file:
        - .env

    drive-select-front:
        build:
            context: .
            dockerfile: ./Front/Dockerfile
        container_name: drive-select-front
        ports:
        - "80:80"
        volumes:
        - .:/usr/src/app/Front
        - /usr/src/app/Front/node_modules
        networks:
        - minha_rede
        env_file:
        - .env


networks:
  minha_rede:
    driver: bridge